= Mes recettes de cuisine

:toc:

[[entrées]]
Entrées
-------

[[pâte-à-beignets-de-mame]]
Pâte à beignets de Mame
~~~~~~~~~~~~~~~~~~~~~~~

_Pour 12 fleurs de courgettes. Préparation : 30 min. Cuisson : 5 min._

*Ingrédients :*

* 1 cuillère à café pleine de sel,
* 1 œuf entier,
* 210 g de farine,
* 250 ml d’eau,
* huile d’olive pour la friture.

*Préparation :*

Mélanger de tout. Y tremper des fleurs de courgettes découpées en 2 ou 3
après avoir enlevé le pistil, ou l’aubergine coupée en rondelles de 0,5
à 1 cm d’épaisseur.

Faire frire dans de l’huile d’olive des deux côtés.

[[guacamole]]
Guacamole
~~~~~~~~~

_Pour 4 personnes. Préparation : 30 min. Réfrigération : 1h._

*Ingrédients :*

* 2 avocats mûrs,
* 2 petites tomates,
* 1 poivron à salade ou 1/2 gros poivron,
* le jus d’un citron,
* 2 cuillères à soupe de cumin moulu,
* 2 cuillères à soupe de coriandre moulue,
* 1 cuillère à café de sel,
* 1 cuillère à café de sauce Tabasco,
* 1 cuillère à soupe de yaourt nature,
* un paquet de chips de maïs.

*Préparation :* Écraser la chair des avocats à la fourchette. Couper les
tomates et le poivron en dès très fins, les ajouter à la chair d’avocat.
Ajouter le jus de citron, les épices, le yaourt et la sauce Tabasco si
nécessaire puis mélanger. Recouvrir le guacamole de jus de citron et
couvrir de film plastique pour éviter que l’avocat noircisse, puis
mettre 1h au frais.

Servir le guacamole avec des chips de maïs, ou bien comme accompagnement
pour des fajitas.

[[cakes]]
Cakes
~~~~~

_Pour 6 personnes. Préparation : 30 min. Cuisson : 45 min._

*Ingrédients :* Base :

* 200 g de farine
* 1 sachet de levure
* 4 œufs
* 5 cl d’huile
* 10 cl de lait
* sel

Exemple de garniture :

* 200g de fêta, olives, thym, (tomates séchées)
* 1 bûche de fromage de chèvre, olives, thym
* Jambon cru, 150 g de fromage râpé

*Préparation :* Mélanger la farine, la levure, les œufs ; délayer avec
le lait et l’huile. Rajouter la garniture. Cuire au four à 200
°C. Vérifier la cuisson après 30 min.

[[pissaladière-de-mamie]]
Pissaladière de Mamie
~~~~~~~~~~~~~~~~~~~~~

_Pour 4 personnes. Préparation : 30 min. Repos : 1 h. Cuisson : 1 h puis
15 min._

*Ingrédients :*

_Pâte :_

* 200 g de farine
* 1 sachet de levure de boulanger
* 15 cl d’eau tiède
* 3 cuillères à soupe d’huile d’olive
* 1,5 cuillères à soupe de margarine
* sel

_Oignons confis :_

* 700 g d’oignons doux
* Huile d’olive
* Sel

_Garniture :_

* 50 g d’olives noires de Nice (Cailletier)


*Préparation :* Faire confire les oignons émincés dans de l’huile
d’olive à feu doux et à couvert pendant environ 1h, avec du sel.

Mélanger la levure de boulanger dans l’eau chaude et laisser reposer
10 min. Mélanger la farine, la margarine, l’eau et la levure, l’huile
d’olive et le sel. Pétrir pour avoir la consistance d’une pâte à pain.
Laisser reposer 1h dans un endroit tiède, ou au four à basse
température.

Étaler la pâte sur un moule à tarte, et percer des trous avec une
fourchette. Répartir dessus les oignons confits, puis les olives.

Cuire au four à 220 °C pendant 15 min, jusqu’à ce
que les oignons soient grillés.

[[cèpes-panés]]
Cèpes panés
~~~~~~~~~~~

_Pour 2 personnes. Préparation : 10 min. Cuisson : 5 min._

*Ingrédients :*

* 200g de cèpes frais
* 1 œuf
* chapelure
* huile de friture
* 1 citron
* sel et poivre

*Préparation :*

Gratter les cèpes au couteau pour les nettoyer, ne pas les mettre dans
l’eau. Les découper en tranches de 1cm d’épaisseur.

Tremper les tranches de cèpes dans l’œuf battu, puis les recouvrir de
chapelure mélangée au set et au poivre.

Les faire frire dans l’huile jusqu’à ce qu’ils soient dorés des deux
côtés.

Servir avec le citron.

[[plats]]
Plats
-----

[[lasagnes]]
Lasagnes
~~~~~~~~

_Pour 4 personnes. Préparation : 30 min. Cuisson : environ 45 min._

*Ingrédients :*

* 400 g de steak hâché
* 600 g de sauce tomate (Barilla basilic)
* 100 g de comté rapé
* 1 oignon
* 50 cL de lait écrémé
* 40 g de maïzena
* noix de muscade
* sel et poivre

*Préparation :* Couper l’oignon en petits morceaux et faire revenir dans
de l’huile d’olive. Quand les oignons ont bien bruni, y ajouter les 400
g de steak haché. Faire cuire à feu moyen puis ajouter la sauce tomate
(on peut ajouter du basilic frais et d’autres épices).

Préparez la béchamel : pour cela, délayez à l’aide d’un fouet,petit à
petit dans une casserole, la maïzena dans le lait froid (opération à
réaliser hors du feu). Placez la casserole sur feu doux et faites
épaissir le tout en mélangeant régulièrement.Une fois la béchamel
épaissie, ajoutez la noix de muscade, le sel et le poivre.

Mélanger la sauce tomate faîte précédemment avec la béchamel. Puis dans
un plat à gratin, verser une couche de cette préparation puis recouvrir
de pâte à lasagne. Refaire la même chose jusqu’à épuisement de la sauce
(environ 2 fois).

La dernière couche doit être une couche de sauce. Ajouter le comté râpé
et faire cuire envrion 45 min à 180° (th.6). Pour
savoir si les lasagnes sont cuites, piquer avec un couteau, les pâtes à
lasagne doivent être fondantes, donc le couteau doit s’enfoncer sans
problème.

[[daube-de-mame]]
Daube de Mame
~~~~~~~~~~~~~

_Pour 8 personnes. Préparation : 30 min. Cuisson : environ 4h30._

*Ingrédients :*

* 2 kg de paleron (ou gîte) de bœuf
* 1 bouteille (75 cl) de vin rouge des Côtes du Rhône
* 1 bouquet garni
* 1 oignons
* 100 g de cèpes séchés
* 200 ml de coulis de tomates
* 2 tomates pelées et épépinées
* 150 g d’olives noires dénoyautées
* 2 cuillère à soupe d’huile d’olive
* 1 cuillère à soupe pleine de farine
* La peau d’une orange

*Préparation :* Faire gonfler les cèpes séchés dans un bol d’eau chaude.
Découper le bœuf en morceaux d’environ 4 cm, émincer les oignons.

Dans une cocote, faire revenir quelques minutes le bœuf et les oignons
dans l’huile d’olive jusqu’à coloration du bœuf. Ajouter ensuite le vin,
la farine, le bouquet garni, le coulis de tomates, les tomates pelées,
les cèpes et l’eau, et la peau d’orange.

Porter à ébullition puis baisser le feux pour rester à une très faible
ébullition. Laisser cuire 4h en remuant toutes les 10 min environ pour
empêcher que la daube ne se colle au fond et brûle. Rajouter de l’eau si
la daube devient trop épaisse.

Enlever le bouquet garni, rajouter les olives et finir la cuisson
15 min. Rectifier l’assaisonnement et servir.

La Daube est meilleure préparée la veille et réchauffée. Elle peut être
servie avec de la polenta ou des raviolis.

[[quiche-au-saumon]]
Quiche au saumon
~~~~~~~~~~~~~~~~

_Pour 6 personnes. Préparation : 30 min. Cuisson : environ 1h15._

*Ingrédients :*

* 1 rouleau de pâte feuilletée
* 200 g de pavé de saumon
* 1 petite courgette
* 1 petit oignon
* 300 ml de lait
* 3 œufs
* 50g d’emmental râpé
* ciboulette
* jus d’un citron
* sel et huile d’olive

*Préparation :*

Faire pré-cuire la pâte feuilletée dans le moule une dizaine de minutes
au four jusqu’à ce qu’elle soit dorée et gonflée.

Faire revenir l’oignon et la courgette émincée dans l’huile d’olive.
Ajouter ensuite le saumon, le jus de citron et la ciboulette.

Mettre les oignons, les courgettes et le saumon dans la pâte. Mélanger
le lait, du sel et les œufs battus, et couvrir la préparation. Finir par
l’emmental râpé.

Cuire environ 40 min à 180 [$^\circ$]C.

[[fajitas]]
Fajitas
~~~~~~~

_Pour 4 personnes. Préparation : 30 min. Cuisson : 30 min._

*Ingrédients :*

* 400 g d’escalopes de poulet ou de dinde
* 2 petits oignons
* 1 poivron rouge ou vert
* 400 g de pulpe de tomate
* 2 cuillères à soupe de cumin
* 2 cuillères à soupe de coriandre
* 2 cuillères à soupe d’huile d’olive
* 1 ou 2 piments oiseau, ou sauce Tabasco
* sel

*Préparation :* Faire revenir dans l’huile le poivron coupé en lanières
et les oignons émincés, puis cuire à couvert. Rajouter le poulet coupé
en lanières, et cuire jusqu’à coloration. Rajouter les tomates, le
cumin, la coriandre, le piment et le sel, et cuire 15 min à feu doux.

Servir avec des tortillas réchauffées, et du guacamole.

[[risotto]]
Risotto
~~~~~~~

_Pour 2 personnes. Préparation : 10 min. Cuisson : environ 20 min._

*Ingrédients :*

* 250 g de riz carnaroli ou Arborio
* 1 oignon
* 1 verre de vin blanc
* 2 bouillons cubes de poule
* 1 l d'eau
* 60g de parmesan
* 250 g de champignons
* 2 cuillères à soupe d'huile d'olive


*Préparation :*

Dans une grande poêle, faire revenir l'oignon émincé dans l'huile, puis ajouter le riz et cuire quelques minutes jusqu'à ce qu'il devienne translucide.
Ajouter le verre de vin blanc.

Dans une casserole à part, dissoudre le cube dans l'eau et ajouter une louche
de ce liquide dans le riz, remuer et rajouter louche par louche (à peu près 20 mn de cuisson).

Faire revenir les champignons à part.
Quand le riz est cuit rajouter le parmesan et les champignons.


[[pâtes-aux-sanguins]]
Pâtes aux sanguins
~~~~~~~~~~~~~~~~~~

_Pour 2 personnes. Préparation : 30 min. Cuisson : 15 min._

*Ingrédients :*

* 150 g de sanguins frais
* persil
* 50g de jambon cru
* 2 petites courgettes
* 300g de tagliatelles fraîches
* huile d’olive

*Préparation :* Laver et nettoyer les sanguins. Les coupes en tranches
d’1 cm. Couper les courgettes en tranches fines, 2 à 3 mm. Les faire
revenir les sanguins, les courgettes et le persil haché dans une poêle à
feu moyen, dans 3 cuillères à soupe d’huile d’olive. Ajouter le jambon
cru à mi cuisson.

Faire cuire les tagliatelles, puis les ajouter dans la poêle avec le
mélange de champignons. Continuer la cuisson quelques minutes et servir.

[[pâtes-dhiver]]
Pâtes d’hiver
~~~~~~~~~~~~~

_Pour 2 personnes. Préparation : 20 min. Cuisson : 20 min._

*Ingrédients :*

* 200g d’Orecchiette
* 1 gros brocolis
* 80g de tomates séchées
* 1 cuillère à soupe de pesto genovese
* 100g de thon en conserve, au naturel
* 10 câpres
* huile d’olive
* thym
* 30g de ricotta salée

*Préparation :*

Mettre les tomates séchées dans de l’eau chaude pendant 10 min. Couper
le brocolis en morceaux de la taille des orechiette, les faire cuire
dans de l’huile d’olive. Ajouter les tomates séchées, le thym, le thon,
le pesto et de l’huile d’olive. Faire cuire les orechiette, puis les
rajouter à la préparation. Finir par de la ricotta salée râpée.

[[porc-au-caramel]]
Porc au caramel
~~~~~~~~~~~~~~~

_Pour 2 personnes. Préparation : 20 min. Cuisson : 20 min._

*Ingrédients :*

* 2 côtes de porc (300 g)
* 90 g de sucre
* 2,5 Cl d’eau
* 1 poivron
* 50 g de noix de cajou
* 1 bouillon cube de légumes
* 1 cuillère à soupe de gingembre moulu
* 1 cuillère à soupe de poivre de Sichuan, légèrement concassé
* 1 cuillère à soupe de mélange quatre épices
* 1 cuillère à soupe d’huile
* 3 cuillère à soupe de sauce soja

*Préparation :*

Découpez le porc en bouchées et faites-le revenir dans l’huile avec le
poivron, juste pour le colorer. Préparez 25 cl d’eau chaude dans un
autre récipient, ajoutez le cube de bouillon de légumes, le gingembre,
le poivre, les épices et la sauce soja. Dans une sauteuse, préparez
votre caramel avec le sucre et l’eau. Une fois le caramel prêt, ajoutez
le bouillon (avec les épices) et tournez très vite pour faire dissoudre
le caramel (qui va se durcir) dans le bouillon.

Une fois dissout, rajoutez la viande et le poivron et mettre à feu vif.
Laissez réduire jusqu’à ce que tout le liquide se soit évaporé (environ
25 min) et que la viande se mêle au mélange épais caramel-épices.
Ajouter les noix de cajou à la fin.

[[desserts-gâteaux]]
Desserts & gâteaux
------------------

[[gâteau-au-yaourt-et-aux-pommes]]
Gâteau au yaourt et aux pommes
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

_Pour 6 personnes. Préparation : 30 min. Cuisson : environ 45 min._

*Ingrédients :*

* 1 pot de yaourt nature (on utilisera le pot vide comme mesure pour les
autres ingrédients)
* 2 pots de sucre brun (cassonade)
* 3 pots de farine
* 3 œufs
* 2 pommes
* 1 sachet de levure chimique

*Préparation :*

Préchauffer le four à 180[$^\circ$] C.

Verser dans un récipient le yaourt, le sucre, la farine et la levure,
les œufs, finir avec les pommes coupées en dés.

Verser dans un moule recouvert de papier sulfurisé, et laisser cuire
environ 45 min.

[[gâteau-aux-carottes]]
Gâteau aux carottes
~~~~~~~~~~~~~~~~~~~

Préchauffer le four Thermostat 5 (environ 150 °C).

Dans un saladier, verser :

* 2 tasse de sucre brun ou roux
* 2 tasses de farine
* 0,5 tasse d’huile
* 1 cuillère à cafe de sel
* 1 cuillère à cafe de cannelle en poudre
* 1 cuillère à cafe de levure chimique
* 2 cuillères à cafe de vanille liquide
* 4 œufs
* 0,5 tasse de noix (ou noix de pecan)
* 0,5 tasse de raisins secs (les faire gonfler dans de l’eau chaude au
préalable)
* 3 tasses de carottes râpées

Faire gonfler les raisins secs dans l’eau chaude.

Mélanger le tout. Verser dans un moule recouvert de papier sulfurisé.
Laisser cuire environ 1 heure.

[[gâteau-au-chocolat]]
Gâteau au chocolat
~~~~~~~~~~~~~~~~~~

* 150 g de chocolat
* 80 g de sucre en poudre
* 2 cuillères à soupe de farine
* 4 blancs d’œufs battus en neige
* 2 jaunes d’œuf
* 100g de beurre
* 50 d’amandes effilées

Battre les blancs en neige. Mélanger le reste des ingrédients dans une
casserole à feu doux. Incorporer les blancs d’œufs en neige. Faire cuire
à environ 170 °C.

[[cookies-demeline]]
Cookies
~~~~~~~

* 100 g de beurre
* 100 g de farine
* 1 œuf
* 100 g de chocolat noir concassé
* 100 g de noisettes concassées
* 75 g de sucre roux

Mélanger le beurre fondu, le sucre, l’ œuf entier, la farine puis
rajouter les noisettes, et le chocolat en dernier.

Déposer des tats de pâte avec une petite cuillère sur la plaque du four
et faire cuire à environ 170°C.

[[mousse-au-chocolat]]
Mousse au chocolat
~~~~~~~~~~~~~~~~~~

_Pour 4 personnes. Préparation : 30 min. Réfrigération : 2h._

* 200 g de chocolat à 70% de cacao
* 6 œufs
* 1 sachet de sucre vanillé

Faire fondre le chocolat au bain marie, et incorporer le sucre et les
jaunes d’œufs hors du feu. Battre les blancs d’œufs en neige ferme, et
les incorporer au chocolat. Verser la mousse dans des verrines, et
mettre au frais au moins deux heures.

[[poires-au-vin]]
Poires au vin
~~~~~~~~~~~~~

_Pour 4 à 8 poires. Préparation : 10 min. Cuisson [$\approx$]
20 min._

* 4 à 8 poires
* 60 cl de vin rouge
* 300 g de sucre
* Épices (vanille, cannelle, poivre …)

Faire bouillir le vin afin de vaporiser l’alcool. Ajouter le sucre et
des épices. Éplucher les poires en gardant la queue, et enlever les
pépins en creusant par dessous.

Mettre les poires à cuire dans le vin épicé environ 20 min, en remuant
afin de colorer toutes les faces des poires.

[[tiramisu-aux-fraises]]
Tiramisu aux fraises
~~~~~~~~~~~~~~~~~~~~

_Pour 4 personnes. Préparation : 20 min. Réfrigération : 2h minimum._

* 200 g de fraises
* 4 biscuits
* 20 g de sucre
* 1 gousse de vanille
* 2 œufs
* 200 g de fromage blanc

Mélanger le fromage blanc et le sucre. Fendre la gousse en deux dans le
sens de la longueur et récupérer les grains. Ajouter au mélange de
fromage blanc, ainsi que les jaunes d’œufs. Faire monter les blancs en
neige et les incorporer au mélange.

Réserver 4 fraises pour la décoration, et mixer le reste pour en faire
un coulis. Émietter un biscuit au fond de chaque verre. Ajouter le
coulis et une couche de fromage blanc. Recommencer l’opération, terminer
par une couche de mélange au fromage blanc et décorer avec une fraise.
Laisser reposer 2h au réfrigérateur.

[[gâteau-roulé-au-citron-et-thé-vert]]
Gâteau roulé au citron et thé vert
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

_Pour 6 personnes. Préparation : 1h30. Réfrigération : 2h minimum._

*Ingrédients pour la génoise roulée*

* 100g de farine
* 1 cuillère à café bombée de thé vert Matcha
* 3 œufs
* 1 cuillère à café de bicarbonate de soude
* [$\frac{1}{4}$] cuillère à café de sel
* 175g de sucre

*Ingrédients pour la crème légère citron*

* 1 citron jaune
* 1 citron vert
* 100g sucre
* 30g Maïzena
* 2 œufs
* 125g mascarpone
* 2 blancs d’œufs
* 1 barquette de framboises fraîches pour le montage

*Préparation de la génoise roulée*

Préparez une grande plaque à pâtisserie (au moins
[$30\times30$] cm) allant au four en la couvrant d’une feuille
de papier sulfurisé. Préchauffez votre four à 180 [$^\circ$]C.

Mélanger ensemble farine, thé, bicarbonate de soude, et sel. Mélangez
bien pour ne pas avoir de grumeaux de thé vert.

Battre les œufs dans le bol de votre mixeur. Incorporez le sucre en 3
fois jusqu’à ce que le mélange blanchisse (ne pas mettre le sucre trop
vite ni toute la quantité d’un seul coup pour aider les œufs à doubler
en volume et à blanchir: littéralement, vos œufs vont changer de couleur
en devenant très clairs et mousseux). Ajoutez le mélange d’ingrédients
secs (ne pas trop mélanger à ce stade, vous pouvez d’ailleurs le faire à
spatule pour plus de délicatesse et éviter de faire tomber le mélange).

Versez sur votre plaque à pâtisserie en formant un grand rectangle de la
taille de votre papier cuisson et cuire environ 12 minutes. Attention à
la cuisson, la génoise ne doit pas trop colorer, sinon elle va devenir
friable en refroidissant et vous aurez du mal à en faire un roulé.

En attendant que la génoise cuise, préparez un grand linge propre de
cuisine, que vous saupoudrez généreusement de sucre glace.

Au bout des 12 minutes, sortez rapidement la génoise et retournez là sur
votre linge recouvert de sucre glace. Roulez le tout en partant du côté
le plus étroit (rouler votre génoise quand elle est encore chaude vous
permet d’avoir un beau roulé qui ne risque pas de se casser lorsque vous
ferez le montage car elle aura déjà pris la forme).

*Préparation de la crème au citron*

Il s’agit ici de réalise une sorte de crème pâtissière au citron.

Zestez finement les citrons et pressez le jus. Versez le jus ainsi
obtenu dans une casserole et rajoutez y le sucre et la Maïzena
(préalablement mélangés ensemble), puis les œufs. Faites chauffer votre
mélange sur feu moyen en ne cessant jamais de mélanger jusqu’à obtention
d’une consistance crémeuse. Débarrasser dans un récipient et couvrez
immédiatement de film étirable. Réservez au frais.

Quand votre crémeux aura refroidi (au moins 30 minutes), montez vos
blancs d’œuf en neige ferme. Sortez le crémeux citron du frigo, battez
légèrement à la fourchette pour éviter les grumeaux et avoir un mélange
lisse. Ajoutez tout d’abord le mascarpone, puis les blancs d’œuf montés,
en mélangeant très délicatement.

Monter le gâteau roulé en recouvrant la génoise de crème au citron et
rouler.

[[fiadone]]
Fiadone
~~~~~~~

_Pour 6 personnes. Préparation : 20 min. Cuisson : 30 min._

* 500g de brocciu corse
* 1 citron ou 1 bergamotte
* 4 œufs
* 110 g de sucre

Écraser le brocciu avec un presse purée. Séparer les blancs des jaunes
d’œufs. Battre les blancs en neige ferme. Mélanger les œufs et les sucre
au brocciu, et le jus d’un demi citron. Incorporer les blancs en neige.

Étaler la préparation dans un plat sur 5 cm d’épaisseur. Cuire 30 min à
200 [$^\circ$]C.

[[rochers-à-la-noix-de-coco]]
Rochers à la noix de coco
~~~~~~~~~~~~~~~~~~~~~~~~~

_Pour 6 personnes. Préparation : 20 min. Cuisson : 15 min._

* 125g de noix de coco râpée
* 90g de sucre
* 2 blanc d’œufs

Mélanger les ingrédients pour former une pâte.

Étaler du papier cuisson sur la plaque du four.

Former dessus de petites pyramides avec la pâte.

Cuire 15 min à 180 [$^\circ$]C, en surveillant pour avoir une
coloration sur les arrêtes des pyramides.


[[gaufres]]
Gaufres
~~~~~~~

_Pour 15 Gaufres. Préparation : 20 min. Repos 30 min. Cuisson : 2 min par Gaufre._

* 200g de farine
* 30g de sucre
* 3 œufs
* 25 cl de lait
* 1 pincée de sel
* 1 cuillère à soupe d'huile de tournesol

Séparer les jaunes et les blanc d'œufs. 

Mettre les blancs dans un saladier et réserver au frais.

Faire blanchir les jaunes et le sucre. Rajouter la farine, le lait et l'huile.
Réserver 1/2h au frais.

Ajouter une pincée de sel aux blancs d'œufs et les monter en neige, puis les incorporer à l'appareil.

Huiler le gaufrier avec un pinceau en sillicone, avant de cuire les gaufres.